### ISSUE TITLE
The mask and category bits seem to be ignored - 1.0.3

### ISSUE THREAD

**Issue by DanJBower** [benzuk/box2d-netstandard#28]
In Version 1.0.3 of the project, the `Filter.MaskBits` and `Filter.CategoryBits` seem to be ignored.

I have created a really simple scene where I have a square and a static floor. I have set the filter data up like below which I expect would allow the square to not collide with the floor as the mask and category bits for each are different.

    FilterData cubeFilter = new() { CategoryBits = 0b0001, MaskBits = 0b0010 };
    FilterData floorFilter = new() { CategoryBits = 0b0100, MaskBits = 0b1000 };

However, the square and the floor still collide and do not pass through each other.

I created the project as a .NET 5 console application.

NuGets

    Install-Package Box2D.NetStandard -Version 1.0.3
    Install-Package Box2D.Window -Version 1.0.3

Code

    using Box2D.Window;
    using Box2DX.Collision;
    using Box2DX.Common;
    using Box2DX.Dynamics;
    using System.Threading;

    namespace Box2dMcve
    {
        internal static class Program
        {
            private static void Main()
            {
                AABB aabb = new();
                aabb.LowerBound.Set(-20, -10);
                aabb.UpperBound.Set(20, 110);

                World world = new(aabb, new Vec2(0.0f, -9.81f), false);

                BodyDef cubeDefinition = new();
                cubeDefinition.Position.Set(0, 70);

                PolygonDef cubeFixture = new();
                cubeFixture.SetAsBox(5, 5);
                cubeFixture.Friction = 0;
                cubeFixture.Restitution = 0;
                cubeFixture.Density = 1;
                FilterData cubeFilter = new() { CategoryBits = 0b0001, MaskBits = 0b0010 };
                cubeFixture.Filter = cubeFilter;

                Body basicCube = world.CreateBody(cubeDefinition);
                basicCube.CreateFixture(cubeFixture);
                basicCube.SetMassFromShapes();

                BodyDef floorDefinition = new();
                floorDefinition.Position.Set(0, 20);

                PolygonDef floorFixture = new();
                floorFixture.SetAsBox(20, 5);
                floorFixture.Friction = 0;
                floorFixture.Restitution = 0;
                FilterData floorFilter = new() { CategoryBits = 0b0100, MaskBits = 0b1000 };
                floorFixture.Filter = floorFilter;

                Body floor = world.CreateBody(floorDefinition);
                floor.CreateFixture(floorFixture);
                floor.SetStatic();

                Thread windowThread = new(() =>
                {
                    SimulationWindow game = new("Physics Simulation", 800, 600);
                    game.UpdateFrame += (_, _) => { world.Step(0.02f, 8, 3); };
                    game.SetView(new CameraView());

                    DrawPhysics physicsDrawer = new(game);
                    physicsDrawer.AppendFlags(DebugDraw.DrawFlags.Aabb);
                    physicsDrawer.AppendFlags(DebugDraw.DrawFlags.Shape);

                    world.SetDebugDraw(physicsDrawer);

                    game.VSync = OpenTK.VSyncMode.Adaptive;
                    game.Run(60, 0);
                });

                windowThread.Start();
            }
        }
    }

**Comment by DanJBower** [comment]
Turns out I hadn't set up a contact filter for the world. I think I just assumed it would do this by default.

Adding the line `world.SetContactFilter(new ContactFilter());` fixes the issue

**Comment by codingben** [comment]
> Turns out I hadn't set up a contact filter for the world. I think I just assumed it would do this by default.
> 
> Adding the line `world.SetContactFilter(new ContactFilter());` fixes the issue

Hi, thank you for opening this issue. Feel free to see how this works with my game and get some ideas:

1. [Physics World Manager](https://github.com/benukhanov/maple-fighters/blob/develop/src/game-service/Game.Application/Physics/PhysicsWorldManager.cs#L34)
2. [Group Contact Filter](https://github.com/benukhanov/maple-fighters/blob/develop/src/game-service/Game.Application/Physics/GroupContactFilter.cs)

And [here](https://github.com/benukhanov/maple-fighters/blob/develop/src/game-service/Game.PhysicsTests/GameTests.cs)'s how it works. Cheers!

**Comment by DanJBower** [comment]
> > Turns out I hadn't set up a contact filter for the world. I think I just assumed it would do this by default.
> > Adding the line `world.SetContactFilter(new ContactFilter());` fixes the issue
> 
> Hi, thank you for opening this issue. Feel free to see how this works with my game and get some ideas:
> 
> 1. [Physics World Manager](https://github.com/benukhanov/maple-fighters/blob/develop/lib/physics/box2d/PhysicsWorldManager.cs#L32)
> 2. [Group Contact Filter](https://github.com/benukhanov/maple-fighters/blob/develop/lib/physics/box2d/GroupContactFilter.cs)
> 
> And [here](https://github.com/benukhanov/maple-fighters/blob/develop/src/game-service/Game.PhysicsTests/GameTests.cs)'s how it works. Cheers!

Thanks for that. It was helpful to see
