### ISSUE TITLE
PolygonDef SetAsBox(....) Angle maybe radian?

### ISSUE THREAD

**Issue by qcbf** [benzuk/box2d-netstandard#30]
test code

```
var b = world.CreateBody(new BodyDef { Position = new Vec2(0, 0), MassData = new MassData { Mass = 0 } });
var s = new PolygonDef();
s.SetAsBox(10, 10, Vec2.Zero, 30 * 0.01745f);
b.CreateFixture(s);
```

need the convert angle to radian, current i test meet expectation, i am correct?
not found need radian in SetAsBox params comment\
thank

**Comment by codingben** [comment]
Hi, yes you need to convert radian to angle, please take a look on this answer [1] and see [2].

[1] https://stackoverflow.com/a/135930
[2] https://www.rapidtables.com/convert/number/radians-to-degrees.html

**Comment by qcbf** [comment]
> Hi, yes you need to convert radian to angle, please take a look on this answer [1] and see [2].
> 
> [1] https://stackoverflow.com/a/135930
> [2] https://www.rapidtables.com/convert/number/radians-to-degrees.html

thank, need unite change angle comment to radian?
may misunderstand angle/radian param comment

**Comment by codingben** [comment]
> > Hi, yes you need to convert radian to angle, please take a look on this answer [1] and see [2].
> > [1] https://stackoverflow.com/a/135930
> > [2] https://www.rapidtables.com/convert/number/radians-to-degrees.html
> 
> thank, need unite change angle comment to radian?
> may misunderstand angle/radian param comment

I don't think we need to change the parameter from angle to radian.

Thank you! :smiley:
