### ISSUE TITLE
Body.DestroyFixture Fails when Fixture is the first in list

### ISSUE THREAD

**Issue by NArnott** [benzuk/box2d-netstandard#38]
I believe I found a bug with `Body.DestroyFixture`. `Body` tracks fixtures using a linked list. When calling `Body.DestroyFixture`, and the fixture to be destroyed is the first fixture in the linked list, m_fixtureList isn't updated, and continues to point to the fixture getting destroyed. This results in Body.m_fixtureList pointing to a single, broken fixture (where both m_body and m_next are null), and all other fixtures are lost (no longer in Body's linked list).

I believe the fix should be simple enough. If the fixture to be destroyed is the first in the linked list, update m_fixtureList to point to that fixture's m_next.

This bug also exists in the C++ implementation, and currently have a thread for it on discord: https://discord.com/channels/460295137705197568/460295137705197570/927374070515900416. Just wanted to track it here as well, as I'm currently halted on my project due to this.

**Comment by codingben** [comment]
A very good find, thanks. Why they don't have an issue for this in the original Box2D repository? If you feel blocked due to this, feel free to fix it here. 😄

**Comment by NArnott** [comment]
Based on the discord channel, it looks like it works fine in the C++ code, based on some pointer magic that automatically updates m_fixtureList without actually referencing it later on. I'll work on a fix for this.

**Comment by codingben** [comment]
@NArnott Interesting. Thank you!
