### ISSUE TITLE
Unable to set CircleShape radius

### ISSUE THREAD

**Issue by ErroneousCreationist** [benzuk/box2d-netstandard#53]
### Description

I'm not sure if I'm missing something, but I can't seem to set the radius of a CircleShape. There isn't a 'Radius' property as is shown in the example, there isn't a way for it to use a CircleDef object.

### How To Reproduce

- Create a CircleShape object `CircleShape shape = new CircleShape();`
- Be unable to set the radius? `shape.Radius //not a thing` 

### Expected Behavior

There should be a 'shape.Radius' property like in the example

**Comment by thomasvt** [comment]
Late response, but I'm closing this because Radius is there. 

The following works fine for me using Box2D.NetStandard Version 2.4.7-alpha:

![image](https://github.com/user-attachments/assets/ca31e25e-45b4-4881-9c1d-e7bace562030)
