### ISSUE TITLE
b2SetLengthUnitsPerMeter or any equivalent doesn't seem to exist yet

### ISSUE THREAD

**Issue by AAM1075** [benzuk/box2d-netstandard#54]
It looks like the function `b2SetLengthUnitsPerMeter` or an equivalent doesn't yet exist. If it does, what's the function name?

**Comment by thomasvt** [comment]
I believe ```b2SetLengthUnitsPerMeter ``` is a feature of the new box2d *v3* . box2d-netstandard is a C# port of "box2d v2"

**Comment by AAM1075** [comment]
I see. I'll close this issue :)
