### ISSUE TITLE
Poly/Poly collision is missed during RubeGoldberg test world run

### ISSUE THREAD

**Issue by Kira-PH** [benzuk/box2d-netstandard#7]
Don't know why yet, other polygon collisions seem to work. There also may be a quirk around the polygons against edges - need to devise another world for that.

**Comment by HughPH** [comment]
![Uploading Peek 2020-06-22 00-08.gif…]()

**Comment by Kira-PH** [comment]
How it's meant to work:
![Peek 2020-06-22 00-08](https://user-images.githubusercontent.com/26636183/85237406-83b64300-b41e-11ea-9b69-922292c5448e.gif)

**Comment by Kira-PH** [comment]
Looks like the polygon does *move* but it doesn't *flip*...

**Comment by Kira-PH** [comment]
It was clipped by the falling beam, not actually hit. Which is odd. I've moved it and tweaked some object properties and everything appears to work now.
