### ISSUE TITLE
DistanceJoint grows over time

### ISSUE THREAD

**Issue by Kira-PH** [benzuk/box2d-netstandard#9]
Evident in RubeGoldberg test world: after the ball hits the ragdoll, the ball gradually sinks lower as it swings.

**Comment by codingben** [comment]
Very, very cool test world. :)

Maybe something is wrong with the box into which the ball falls?

**Comment by codingben** [comment]
> Very, very cool test world. :)
> 
> Maybe something is wrong with the box into which the ball falls?

I'm talking about this situation: 

https://gyazo.com/e4af9258264b3731d323f677860ee4d9

The test ends when the ball stops moving.

**Comment by codingben** [comment]
I think we need gyazo :P

**Comment by Kira-PH** [comment]
No, run a Release build or enable code optimisation, and don't use debugging. It's the large ball that falls at the end.

**Comment by Kira-PH** [comment]
Why do I need Gyazo? I have Spectacle, Peek and OBS!

**Comment by Kira-PH** [comment]
> Very, very cool test world. :)

It's an example from Chris Campbell's RUBE software: https://www.iforce2d.net/rube/
I added a link to Chris' Box2D tutorials in the documentation, too.

**Comment by Kira-PH** [comment]
Fixed: DistanceJoint.SolvePositionConstraints was using the 2008 Box2DX code, now up-to-date.
